### ISSUE TITLE
Cases Generated from FogBugz disappear in Mylyn Task List

### ISSUE THREAD

**Issue by lhughes41** [Tasktop/Foglyn#41]
I'm noticing strange behavior with tasks generated from eclipse mylyn task list interface versus those created as "cases" on Fogbugz inbox. The latter appear when syncing to Fogbugz but eventually disappear for no apparent reason even though I can still seem then in my inbox. These includes active cases. On the other hand the tasks I created within the eclipse mylyn task list interface seem to stick around both in the interface and in my fogbugz inbox (I did a 'submitt').

  Two clues maybe:
1) bug versus query -- I notice that cases created in inbox of Fogbugz are "bugs" whereas the ones I am uploading from eclipse are "queries."  Presumably this is influnecing the vanishing?
2)mylyn context hiding -- I've had a similar problem with task queries vanishing in the task interface in eclipse but "alt-clicking" made them appear again.  So mylyn was involved...  but this does not help the issue I see here and am posting about. Just thought I'd mention in case some how mylyn context hiding is playing a part in this issue.

I can work around by only doing tasks from eclipse not fogbugz but I would think Fogbugz would like things to work from items created in their interface online as well :-)

I am running Eclipse 3.7 fully uptodate. I have mylyn installed and the foglyn plugin fully uptodate.

thanks,
 Luke
p.s. I tried different query views like "My Cases" and "FIlter: inbox" but doesn't fix.

**Comment by lhughes41** [comment]
OK I just figured this one out (as always happens after issue posting). Leaving answer here for other newbies in future. The key is to click the "Focus on Workweek" button off in the panel of buttons at the top of the task list view. This reveals all cases and tasks.

**Comment by pstibrany** [comment]
I was going to suggest desktop sharing debug session, because Mylyn/Foglyn never removes tasks on its own. (Tasks that don't match any query go to Unmatched group). I'm glad you found the solution.

**Comment by lhughes41** [comment]
Thanks for taking time to reply Peter.
 Luke

-----Original Message-----
