### ISSUE TITLE
User ID Field is not being recognized

### ISSUE THREAD

**Issue by somughosh** [Tasktop/Foglyn#45]
Hi,

I am trying FogBugz on Juno... When I use Foglyn connector, I get an error saying User name cannot be empty. However there is a valid value in that field. This is probably because that field is not read correctly by the plugin. 

Can you please provide a workaround or suggestion on what I can do to fix it

Thanks
Somu

**Comment by pstibrany** [comment]
Hi,
can you please send a screenshot showing the issue? I've tried to install Foglyn into Eclipse Juno today (with Mylyn 3.8), and had no problem creating a new repository.

**Comment by somughosh** [comment]
Hi,

Thanks for looking into this. Here is a screenshot

<table style="width:auto;"><tr><td><a href="https://picasaweb.google.com/lh/photo/oV0jVzm-h4o_S01_6232StMTjNZETYmyPJy0liipFm0?feat=embedwebsite"><img src="https://lh4.googleusercontent.com/-O34iEjPYPJA/T-FL-oj0BNI/AAAAAAAACSM/fKMqtE5yXzo/s144/FogLynError.png" height="135" width="144" /></a></td></tr><tr><td style="font-family:arial,sans-serif; font-size:11px; text-align:right">From <a href="https://picasaweb.google.com/110820949442633458005/FogBugzFogLynDebug?authuser=0&feat=embedwebsite">FogBugz/FogLyn Debug</a></td></tr></table>

**Comment by somughosh** [comment]
Hi,

Nevermind. This got resolved with the newer Maven!

Thanks
Somu

**Comment by pstibrany** [comment]
Thanks for update. I don't quite understand how Maven can affect this, but I'm glad it works for you now.
