### ISSUE TITLE
Create Foglyn for PHPStorm

### ISSUE THREAD

**Issue by ghost** [Tasktop/Foglyn#49]
Hi,

I wanted to ask whether it is possible to create this amazing plugin for PHPStorm?

Would love to see such a great integration in another IDE...

Best

Sebastian Tischer

**Comment by pstibrany** [comment]
Hi, that is unfortunately out of scope of this project. PHPStorm is based on IntelliJ platform, which is completely different from Eclipse. Btw, IntelliJ and PHPStorm already has integration with issue trackers as part of its task management feature, and there is also FogBugz integration too.
